routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', function(){
    Auth::logout();
    return redirect('/');
});

Auth::routes();

Route::get('/empreendimento', 'EmpreendimentoController@index');
Route::get('/empreendimento/detail/{id}', 'EmpreendimentoController@detail');

Route::get('/cliente/adicionar', 'ClienteController@create');
Route::get('/cliente/editar/{id}','ClienteController@edit');
Route::get('/cliente', 'ClienteController@index');
Route::get('/cliente/detail/{id}', 'ClienteController@detail');
Route::post('/cliente/store', 'ClienteController@store');

Route::get('/cidades/por-estado/{id}', 'CidadeController@getByEstado');


Route::group(['middleware' => ['web', 'FiltraAdmin']], function(){
   Route::get('/vendedor/adicionar', 'VendedorController@create');
   Route::get('/vendedor/editar/{id}','VendedorController@edit');
   Route::get('/vendedor', 'VendedorController@index');
   Route::get('/vendedor/detail/{id}', 'VendedorController@detail');
   Route::post('/vendedor/store', 'VendedorController@store');
   
   Route::resource('imobiliaria', 'ImobiliariaController');
   Route::get('/imobiliaria/detail/{id}', 'ImobiliariaController@show');

   Route::get('/trilhadevenda', 'TrilhaDeVendaController@index');
   Route::get('/trilhadevenda/adicionar', 'TrilhaDeVendaController@create');
   Route::post('/trilhadevenda/store','TrilhaDeVendaController@store');
   Route::get('/trilhadevenda/editar/{id}', 'TrilhaDeVendaController@edit');
   Route::get('/trilhadevenda/detail/{id}', 'TrilhaDeVendaController@detail');
   Route::get('/trilhadevenda/config/{id}','TrilhaDeVendaController@config');
   Route::post('/trilhadevenda/salvarconfig','TrilhaDeVendaController@salvarConfig');

   Route::get('/etapa', 'EtapaController@index');
   Route::get('/etapa/adicionar','EtapaController@create');
   Route::get('/etapa/detail/{id}','EtapaController@detail');
   Route::post('/etapa/store','EtapaController@store');
   
   Route::get('/empreendimento/adicionar', 'EmpreendimentoController@create');
   Route::get('/empreendimento/editar/{id}','EmpreendimentoController@edit');
   Route::post('/empreendimento/store', 'EmpreendimentoController@store');
   Route::post('/empreendimento/update/{id}', 'EmpreendimentoController@update');
});

Route::get('/venda', 'VendaController@index');
Route::post('/venda', 'VendaController@index');
Route::get('/venda/detail/{id}','VendaController@detail');
Route::get('/venda/adicionar', 'VendaController@create');
Route::post('/venda/store', 'VendaController@store');
Route::get('/venda/{id}/concluir-etapa-em-andamento', 'VendaController@concluirEtapaEmAndamento');
Route::get('/venda/{id}/excluirJustificativa', 'VendaController@excluirJustificativa');
Route::get('/venda/{id}/salvarJustificativa/{texto}', 'VendaController@salvarJustificativa');
Route::get('/venda/{vendaId}/mudar-status-subetapa/{subEtapId}', 'VendaController@mudarStatusSubEtapa');
Route::get('/venda/{id}/mudar-status/{status}', 'VendaController@mudarStatusVenda');
Route::get('/pendencias','VendaController@pendencies');

Route::get('/logs', 'LogController@index');

Route::get('/home', 'HomeController@index')->name('home');

app/Imobiliaria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Imobiliaria extends Model
{
    protected $guarded = ['id'];
   
    public function vendedores()
    {
        return $this->hasMany('App\User');
    }

    public function cidade()
    {
        return $this->belongsTo('App\Cidade');
    }
}

app/Http/Controllers/ImobiliariaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Imobiliaria;
use App\Estado;
use App\Cidade;

class ImobiliariaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $registros = Imobiliaria::all();
//       dd($registros);
       return view('imobiliarias.index',['registros' => $registros]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $estados = Estado::all();
        return view('imobiliarias.create', ['estados' => $estados]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request,['nome'=> 'required|max:255', 
                                 'cidade_id' => 'required|numeric',]);

        if(isset($request->id)){
            $registro = Imobiliaria::findOrFail($request->id);
            activity()
                ->by(Auth::id())
                ->on($registro)
                ->log("Editou a imobiliária " . $registro->nome);
        } else {
            $registro = new Imobiliaria();
            activity()
                ->by(Auth::id())
                ->on($registro)
                ->log("Cadastrou a imobiliária " . $request->nome);
        }

        $registro->fill($request->all());       
        $registro->save();

        $request->session()->flash('success', 'Imobiliária cadastrada com sucesso');

        return redirect()->action('ImobiliariaController@index');
//        return redirect()->route('imobiliarias.index');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $registro = Imobiliaria::with('cidade')->findOrFail($id);
        return view('imobiliarias.detail',['registro' => $registro]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $estados = Estado::all();
       $registro = Imobiliaria::with('cidade.estado')->findOrFail($id);
       $cidades = Cidade::where("estado_id", $registro->toArray()['cidade']['estado_id'])->get();
       
       return view('imobiliarias.create',['registro' => $registro, 'estados' => $estados, 'cidades' => $cidades]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $this->validate($request,['nome'=> 'required',]);
       
       $registro = Imobiliaria::findOrFail($id);
       
       $registro->nome = $request->nome;
       $registro->save();
       
       return redirect()->route('imobiliarias.index')->with('alert-success','Registro atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $registro = Imobiliaria::findOrFail($id);
       
       if ($registro->vendedores()->count() > 0){
          return redirect()->route('imobiliaria.index')->with('alert-success','O registro não pode ser excluído, pois possui vendedores cadastrados');
       } else{
          $registro->delete();
          return redirect()->route('imobiliarias.index')->with('alert-success','Registro excluído com sucesso!');
       }
    }
}

resources/views/imobiliarias/create.blade.php
@extends('layouts.logged')
@section('title', 'Cadastro de Imobiliária')
@section('content')
<div class="grid-x grid-padding-x">
    <div class="medium-12 cell">
        <h3>{{isset($registro) ? 'Editar' : 'Cadastrar'}} Imobiliária</h3>
    </div>
</div>
<form role="form" method="post" action="{{route('imobiliaria.store')}}">
   {{ csrf_field() }}
   @if(isset($registro))
   <input name="id" value="{{$registro->id}}" type="hidden">
   @endif
   <div class="grid-x grid-padding-x">
       <div class="medium-4 cell">
           <label>
               Nome
               <input type="text" name="nome" value="{{old('nome') ?: $registro->nome ?? ''}}">
               @component('components.form-errors',['field' => 'nome'])
               @endcomponent
           </label>
      </div>
           
      <div class="medium-4 cell">
          <label>
              Telefone
              <input type="text" name="telefone" value="{{old('telefone') ?: $registro->telefone ?? ''}}">
          </label>
      </div>

      <div class="medium-4 cell">
          <label>
              Email
              <input type="text" name="email" value="{{old('email') ?: $registro->email ?? ''}}">
              @component('components.form-errors',['field' => 'email'])
              @endcomponent
          </label>
      </div>

      <div class="medium-4 cell">
          <label>
              Endereço
              <input type="text" name="endereco" value="{{old('endereco') ?: $registro->endereco ?? ''}}">
              @component('components.form-errors',['field' => 'endereco'])
              @endcomponent
          </label>
      </div>

      @component('components.cidades',['estados' => $estados])
      @endcomponent
   
    <div class="medium-12 cell small-12">
        <button class="button" type="submit">Enviar</button>
    </div>
</div>
</form>
@endsection

@isset($registro)
@section('footer')
    <script type="text/javascript">
        $(document).ready(function(){
            $("#select-estados").val({{$registro->cidade->estado->id}});
            $("#select-estados").trigger("change");
            setTimeout(function(){
                $("#select-cidades").val({{$registro->cidade->id}});
            },4000);
        });
    </script>
@endsection
@endisset

resources/views/imobiliarias/detail.blade.php
<div class="grid-x grid-padding-x">
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="grid-x">
        <div class="grid-x grid-padding-x">
            <div class="medium-12 cell">
                <h3> Detalhe da imobiliária <small>{{$registro->nome}}</small></h3>
            </div>
        </div>
       <div class="medium-12 cell">
            <dl>
                <dt>Endereço</dt>
                <dd>{{$registro->endereco ?: "Não definido"}}</dd>
          </dl>
       </div>
        <div class="medium-6 cell">
            <dl>
                <dt>Email</dt>
                <dd>{{$registro->email ?: "Não definido"}}</dd>
                <dt>Telefone</dt>
                <dd>{{$registro->telefone ?: "Não definido"}}</dd>
            </dl>
        </div>
        <div class="medium-6 cell">
            <dl>
                <dt>Cidade</dt>
                <dd>{{$registro->cidade->cidade ?: "Não definido"}}</dd>
                <dt>Estado</dt>
                <dd>{{$registro->cidade->estado->sigla ?: "Não definido"}}</dd>
            </dl>
        </div>
        <div class="medium-12 cell">
            <a href="{{action('ImobiliariaController@edit',['id' => $registro->id])}}" class="button secondary">Editar</a>
        </div>
    </div>
</div>

resources/views/imobiliarias/index.blade.php
@extends('layouts.logged')
@section('title', 'Imobiliárias')
@section('content')
<div class="grid-x grid-padding-x grid-padding-y">
    <div class="auto cell">
        <h3 style="display: inline;">Imobiliária</h3>
        <a class="button" href="{{action('ImobiliariaController@create')}}">Cadastrar</a>
    </div>
    <div class="auto cell">

    </div>
</div>
<div class="grid-x grid-padding-x grid-padding-y">
    <div class="medium-12 cell">
        @if(count($registros) > 0)
        <table class="hover ajax-modal-table" data-modal="#imobiliaria-detail-modal" data-route="/imobiliaria/detail">
            <thead>
                <tr>
                    <td>Nome</td>
                    <td>Telefone</td>
                    <td>Endereço</td>
                    <td>E-mail</td>
                </tr>
            </thead>
            <tbody  data-open="cliente-detail-modal">
            @foreach($registros as $registro)
                <tr data-entity-id="{{$registro->id}}">
                    <td>{{$registro->nome}}</td>
                    <td>{{$registro->telefone}}</td>
                    <td>{{$registro->endereco}}</td>
                    <td>{{$registro->email}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @else
        @component('components.nenhum-resultado',['link' => 'ImobiliariaController@create'])
        @endcomponent
        @endif
    </div>
</div>
@endsection

<div class="reveal" id="imobiliaria-detail-modal" data-reveal>

</div>